### ISSUE TITLE
How to run mhaPlanner ?

### ISSUE THREAD

**Issue by anirudha615** [shivamvats/sbpl-intern-log#1]
Hey, can you please guide me on how to run a mha planner through sbpl. I am able to work with arastar,anastar,etc but could not run the mhaPlanner.

**Comment by shivamvats** [comment]
@anirudha615 You should raise sbpl related issues on the sbpl repository. 
You may refer to https://github.com/shivamvats/monolithic_pr2_planner. It uses mha_planner.
